<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Capítulo 8. Revisiones sistemáticas y la declaración PRISMA – Buscar antecedentes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/09-busqueda-por-citas.html" rel="next">
<link href="../capitulos/07-pregunta-pico.html" rel="prev">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e8095de49e5089c8f049b1de2731477f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-71a456e21126f1848a2771ab6d261018.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e8095de49e5089c8f049b1de2731477f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-860e87ae41dabe76a663c1efdd0f8936.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-69c9dbb93d3efb48ba33545d424ca74f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-860e87ae41dabe76a663c1efdd0f8936.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/07-pregunta-pico.html">Parte III. Búsqueda sistemática</a></li><li class="breadcrumb-item"><a href="../capitulos/08-revisiones-y-prisma.html"><span class="chapter-title">Capítulo 8. Revisiones sistemáticas y la declaración PRISMA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Buscar antecedentes</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/toninif/libro-busqueda-cientifica" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I. Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/01-antecedentes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 1. Qué son los antecedentes y por qué buscarlos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/02-planificar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 2. Planificar la búsqueda</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/03-donde-buscar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 3. Dónde buscar: fuentes y herramientas clásicas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II. Técnicas de búsqueda</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/04-busqueda-por-terminos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 4. Búsqueda por términos: palabras clave y vocabulario controlado</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/05-operadores-y-cadenas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 5. Operadores y cadenas de búsqueda</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/06-espanol-e-ingles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 6. Buscar en español y en inglés</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III. Búsqueda sistemática</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/07-pregunta-pico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 7. La pregunta PICO y sus variantes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/08-revisiones-y-prisma.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Capítulo 8. Revisiones sistemáticas y la declaración PRISMA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/09-busqueda-por-citas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 9. Búsqueda por citas y estrategias complementarias</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IV. Inteligencia artificial, evaluación y escritura</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/10-inteligencia-artificial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 10. Inteligencia artificial para la búsqueda de antecedentes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/11-evaluar-fuentes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 11. Evaluar lo que encontramos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/12-gestionar-y-escribir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 12. Gestionar referencias y escribir los antecedentes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../anexos/A-plantillas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Anexo A. Plantillas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../anexos/B-glosario.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Anexo B. Glosario</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../anexos/C-recursos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Anexo C. Directorio de recursos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../anexos/D-bibliografia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Anexo D. Bibliografía</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#tipos-de-revisiones" id="toc-tipos-de-revisiones" class="nav-link active" data-scroll-target="#tipos-de-revisiones">8.1 Tipos de revisiones</a></li>
  <li><a href="#etapas-de-una-revisión-sistemática" id="toc-etapas-de-una-revisión-sistemática" class="nav-link" data-scroll-target="#etapas-de-una-revisión-sistemática">8.2 Etapas de una revisión sistemática</a>
  <ul class="collapse">
  <li><a href="#pregunta" id="toc-pregunta" class="nav-link" data-scroll-target="#pregunta">1. Pregunta</a></li>
  <li><a href="#protocolo-y-registro" id="toc-protocolo-y-registro" class="nav-link" data-scroll-target="#protocolo-y-registro">2. Protocolo y registro</a></li>
  <li><a href="#búsqueda" id="toc-búsqueda" class="nav-link" data-scroll-target="#búsqueda">3. Búsqueda</a></li>
  <li><a href="#gestión-de-resultados" id="toc-gestión-de-resultados" class="nav-link" data-scroll-target="#gestión-de-resultados">4. Gestión de resultados</a></li>
  <li><a href="#cribado-por-título-y-resumen" id="toc-cribado-por-título-y-resumen" class="nav-link" data-scroll-target="#cribado-por-título-y-resumen">5. Cribado por título y resumen</a></li>
  <li><a href="#evaluación-del-texto-completo" id="toc-evaluación-del-texto-completo" class="nav-link" data-scroll-target="#evaluación-del-texto-completo">6. Evaluación del texto completo</a></li>
  <li><a href="#extracción-de-datos" id="toc-extracción-de-datos" class="nav-link" data-scroll-target="#extracción-de-datos">7. Extracción de datos</a></li>
  <li><a href="#evaluación-del-riesgo-de-sesgo-o-de-la-calidad" id="toc-evaluación-del-riesgo-de-sesgo-o-de-la-calidad" class="nav-link" data-scroll-target="#evaluación-del-riesgo-de-sesgo-o-de-la-calidad">8. Evaluación del riesgo de sesgo o de la calidad</a></li>
  <li><a href="#síntesis" id="toc-síntesis" class="nav-link" data-scroll-target="#síntesis">9. Síntesis</a></li>
  <li><a href="#certeza-de-la-evidencia" id="toc-certeza-de-la-evidencia" class="nav-link" data-scroll-target="#certeza-de-la-evidencia">10. Certeza de la evidencia</a></li>
  <li><a href="#reporte" id="toc-reporte" class="nav-link" data-scroll-target="#reporte">11. Reporte</a></li>
  </ul></li>
  <li><a href="#qué-es-prisma" id="toc-qué-es-prisma" class="nav-link" data-scroll-target="#qué-es-prisma">8.3 ¿Qué es PRISMA?</a></li>
  <li><a href="#la-lista-de-verificación-prisma-2020" id="toc-la-lista-de-verificación-prisma-2020" class="nav-link" data-scroll-target="#la-lista-de-verificación-prisma-2020">8.4 La lista de verificación PRISMA 2020</a></li>
  <li><a href="#el-diagrama-de-flujo-prisma-2020" id="toc-el-diagrama-de-flujo-prisma-2020" class="nav-link" data-scroll-target="#el-diagrama-de-flujo-prisma-2020">8.5 El diagrama de flujo PRISMA 2020</a></li>
  <li><a href="#extensiones-de-prisma" id="toc-extensiones-de-prisma" class="nav-link" data-scroll-target="#extensiones-de-prisma">8.6 Extensiones de PRISMA</a></li>
  <li><a href="#herramientas-para-gestionar-una-revisión" id="toc-herramientas-para-gestionar-una-revisión" class="nav-link" data-scroll-target="#herramientas-para-gestionar-una-revisión">8.7 Herramientas para gestionar una revisión</a></li>
  <li><a href="#revisión-sistemática-en-un-trabajo-de-grado" id="toc-revisión-sistemática-en-un-trabajo-de-grado" class="nav-link" data-scroll-target="#revisión-sistemática-en-un-trabajo-de-grado">8.8 ¿Revisión sistemática en un trabajo de grado?</a></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#actividad" id="toc-actividad" class="nav-link" data-scroll-target="#actividad">Actividad</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/07-pregunta-pico.html">Parte III. Búsqueda sistemática</a></li><li class="breadcrumb-item"><a href="../capitulos/08-revisiones-y-prisma.html"><span class="chapter-title">Capítulo 8. Revisiones sistemáticas y la declaración PRISMA</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Capítulo 8. Revisiones sistemáticas y la declaración PRISMA</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>En este capítulo vas a aprender:</strong></p>
<ul>
<li>qué tipos de revisiones de la literatura existen y en qué se diferencian;</li>
<li>cuáles son las etapas de una revisión sistemática;</li>
<li>qué es PRISMA 2020, qué exige y cómo se arma el diagrama de flujo;</li>
<li>qué extensiones de PRISMA existen (PRISMA-S, PRISMA-ScR, PRISMA-P);</li>
<li>qué herramientas facilitan el cribado y la evaluación de estudios;</li>
<li>qué versión “posible” de revisión sistemática es realista para un trabajo de grado.</li>
</ul>
<hr>
<section id="tipos-de-revisiones" class="level2">
<h2 class="anchored" data-anchor-id="tipos-de-revisiones">8.1 Tipos de revisiones</h2>
<p>“Revisión de la literatura” es un término paraguas. Grant y Booth (2009) identificaron catorce tipos distintos. Los más relevantes para estudiantes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Objetivo</th>
<th>Búsqueda</th>
<th>Evaluación de calidad</th>
<th>Síntesis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Narrativa (tradicional)</strong></td>
<td>Panorama de un tema</td>
<td>No necesariamente exhaustiva ni explícita</td>
<td>Opcional</td>
<td>Narrativa, a criterio del autor</td>
</tr>
<tr class="even">
<td><strong>Sistemática</strong></td>
<td>Responder una pregunta precisa con toda la evidencia disponible</td>
<td>Exhaustiva, explícita, reproducible</td>
<td>Sí, con herramientas formales</td>
<td>Narrativa estructurada o metaanálisis</td>
</tr>
<tr class="odd">
<td><strong>Metaanálisis</strong></td>
<td>Combinar estadísticamente los resultados de varios estudios</td>
<td>Como la sistemática (suele ser parte de ella)</td>
<td>Sí</td>
<td>Estadística</td>
</tr>
<tr class="even">
<td><strong>De alcance (<em>scoping review</em>)</strong></td>
<td>Mapear qué se investigó sobre un tema amplio y detectar vacíos</td>
<td>Exhaustiva</td>
<td>Generalmente no</td>
<td>Mapa, tablas, categorías</td>
</tr>
<tr class="odd">
<td><strong>Rápida (<em>rapid review</em>)</strong></td>
<td>Dar una respuesta en poco tiempo (por ejemplo, para una decisión política)</td>
<td>Simplificada y declarada</td>
<td>Simplificada</td>
<td>Narrativa</td>
</tr>
<tr class="even">
<td><strong>Paraguas (<em>umbrella review</em>)</strong></td>
<td>Sintetizar revisiones sistemáticas existentes</td>
<td>En bases de revisiones</td>
<td>Sí (de las revisiones)</td>
<td>Narrativa o estadística</td>
</tr>
<tr class="odd">
<td><strong>Sistematizada</strong></td>
<td>Aplicar elementos del método sistemático con recursos limitados (típica de tesis)</td>
<td>Estructurada y documentada, pero acotada</td>
<td>Parcial</td>
<td>Narrativa</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled" title="Revisión sistemática no es sinónimo de 'revisión con muchas referencias'">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota al margen</span>Revisión sistemática no es sinónimo de ‘revisión con muchas referencias’
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lo que la define es el <strong>método</strong>: una pregunta explícita, una búsqueda reproducible, criterios de selección fijados de antemano, evaluación de la calidad de los estudios y una síntesis transparente.</p>
</div>
</div>
</section>
<section id="etapas-de-una-revisión-sistemática" class="level2">
<h2 class="anchored" data-anchor-id="etapas-de-una-revisión-sistemática">8.2 Etapas de una revisión sistemática</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
    A["1. Pregunta&lt;br/&gt;(PICO o variante)"] --&gt; B["2. Protocolo y registro&lt;br/&gt;(PROSPERO, OSF)"]
    B --&gt; C["3. Búsqueda&lt;br/&gt;(varias bases, literatura gris, citas)"]
    C --&gt; D["4. Gestión de resultados&lt;br/&gt;(exportar, eliminar duplicados)"]
    D --&gt; E["5. Cribado por título y resumen&lt;br/&gt;(dos revisores independientes)"]
    E --&gt; F["6. Evaluación del texto completo&lt;br/&gt;(con motivos de exclusión)"]
    F --&gt; G["7. Extracción de datos"]
    G --&gt; H["8. Evaluación del riesgo de sesgo"]
    H --&gt; I["9. Síntesis&lt;br/&gt;(narrativa o metaanálisis)"]
    I --&gt; J["10. Certeza de la evidencia&lt;br/&gt;(p. ej., GRADE)"]
    J --&gt; K["11. Reporte&lt;br/&gt;(PRISMA 2020)"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="pregunta" class="level3">
<h3 class="anchored" data-anchor-id="pregunta">1. Pregunta</h3>
<p>Formulada con PICO o alguna de sus variantes (capítulo 7).</p>
</section>
<section id="protocolo-y-registro" class="level3">
<h3 class="anchored" data-anchor-id="protocolo-y-registro">2. Protocolo y registro</h3>
<p>El <strong>protocolo</strong> es un documento escrito <strong>antes</strong> de empezar que describe la pregunta, los criterios de inclusión, las fuentes, la estrategia de búsqueda, el método de selección, la evaluación de calidad y la síntesis prevista. Sirve para evitar decisiones arbitrarias a mitad de camino.</p>
<p>El protocolo se <strong>registra</strong> públicamente:</p>
<ul>
<li><strong>PROSPERO</strong>: registro internacional de revisiones sistemáticas con un resultado relacionado con la salud.</li>
<li><strong>OSF Registries</strong> (<em>Open Science Framework</em>): para cualquier disciplina, incluidas las revisiones de alcance.</li>
</ul>
<p>Para redactar el protocolo existe la guía <strong>PRISMA-P</strong> (Moher et al., 2015).</p>
</section>
<section id="búsqueda" class="level3">
<h3 class="anchored" data-anchor-id="búsqueda">3. Búsqueda</h3>
<p>Todo lo visto en los capítulos 3 a 6, más la búsqueda por citas y la literatura gris (capítulo 9). En una revisión sistemática se espera:</p>
<ul>
<li>varias bases de datos, incluidas las disciplinares con tesauro;</li>
<li>estrategias adaptadas a cada base y <strong>reportadas completas</strong>;</li>
<li>búsqueda en español, inglés y otros idiomas pertinentes, o una justificación si no se hace;</li>
<li>registro de la fecha de cada búsqueda;</li>
<li>idealmente, revisión de la estrategia por un bibliotecario (guía PRESS, capítulo 5).</li>
</ul>
</section>
<section id="gestión-de-resultados" class="level3">
<h3 class="anchored" data-anchor-id="gestión-de-resultados">4. Gestión de resultados</h3>
<p>Los resultados de todas las bases se exportan (en formato RIS, BibTeX u otro) a un gestor bibliográfico o a una herramienta de cribado, y se <strong>eliminan los duplicados</strong>. Hay que anotar cuántos registros vinieron de cada fuente y cuántos duplicados se quitaron: esos números van al diagrama PRISMA.</p>
</section>
<section id="cribado-por-título-y-resumen" class="level3">
<h3 class="anchored" data-anchor-id="cribado-por-título-y-resumen">5. Cribado por título y resumen</h3>
<p>Se leen títulos y resúmenes y se decide, con los criterios de inclusión en la mano, si cada registro:</p>
<ul>
<li><strong>se excluye</strong> (claramente no cumple los criterios);</li>
<li><strong>pasa</strong> a la siguiente etapa (cumple o hay dudas).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="En caso de duda, se incluye">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Pista</span>En caso de duda, se incluye
</div>
</div>
<div class="callout-body-container callout-body">
<p>En el cribado por título y resumen, el error más costoso es excluir un estudio relevante: ya no vuelve a aparecer. Un estudio dudoso que pasa se descarta después con el texto completo.</p>
</div>
</div>
<p>Buenas prácticas:</p>
<ul>
<li><strong>Prueba piloto</strong>: antes de empezar, dos personas criban el mismo conjunto de 50 a 100 registros y comparan decisiones para afinar la interpretación de los criterios.</li>
<li><strong>Doble revisión independiente</strong>: dos personas criban por separado y luego resuelven los desacuerdos por consenso o con una tercera persona.</li>
<li><strong>Acuerdo entre revisores</strong>: suele medirse con el coeficiente <strong>kappa de Cohen</strong> (Cohen, 1960). Como orientación, valores entre 0,61 y 0,80 se consideran un acuerdo sustancial y por encima de 0,80, casi perfecto (Landis y Koch, 1977).</li>
</ul>
</section>
<section id="evaluación-del-texto-completo" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-del-texto-completo">6. Evaluación del texto completo</h3>
<p>Se consiguen los textos completos de los registros que pasaron el cribado y se leen para tomar la decisión final. Ahora <strong>cada exclusión se registra con su motivo</strong> (población no pertinente, sin grupo control, etc.), porque PRISMA pide reportarlos.</p>
</section>
<section id="extracción-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="extracción-de-datos">7. Extracción de datos</h3>
<p>Con una planilla diseñada de antemano (y probada con dos o tres estudios), se extraen los datos de cada estudio incluido: autores, año, país, diseño, muestra, intervención, comparación, instrumentos, resultados, financiamiento, etc. La matriz del <a href="../anexos/A-plantillas.html">Anexo A</a> es un buen punto de partida.</p>
</section>
<section id="evaluación-del-riesgo-de-sesgo-o-de-la-calidad" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-del-riesgo-de-sesgo-o-de-la-calidad">8. Evaluación del riesgo de sesgo o de la calidad</h3>
<p>Se evalúa con herramientas específicas para cada diseño:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Diseño de los estudios incluidos</th>
<th>Herramientas frecuentes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ensayos controlados aleatorizados</td>
<td>RoB 2 (Sterne et al., 2019)</td>
</tr>
<tr class="even">
<td>Estudios no aleatorizados de intervenciones</td>
<td>ROBINS-I</td>
</tr>
<tr class="odd">
<td>Estudios observacionales (cohortes, casos y controles)</td>
<td>Escala Newcastle-Ottawa, listas de JBI</td>
</tr>
<tr class="even">
<td>Estudios cualitativos</td>
<td>CASP, listas de JBI</td>
</tr>
<tr class="odd">
<td>Estudios de métodos mixtos</td>
<td>MMAT (Hong et al., 2018)</td>
</tr>
<tr class="even">
<td>Revisiones sistemáticas</td>
<td>AMSTAR 2</td>
</tr>
</tbody>
</table>
</section>
<section id="síntesis" class="level3">
<h3 class="anchored" data-anchor-id="síntesis">9. Síntesis</h3>
<ul>
<li><strong>Síntesis narrativa estructurada</strong>: se agrupan los estudios (por tipo de intervención, población, resultado) y se describen patrones, coincidencias y contradicciones. Existe una guía de reporte para síntesis sin metaanálisis: <strong>SWiM</strong>.</li>
<li><strong>Metaanálisis</strong>: si los estudios son suficientemente homogéneos, se combinan estadísticamente sus resultados.</li>
</ul>
</section>
<section id="certeza-de-la-evidencia" class="level3">
<h3 class="anchored" data-anchor-id="certeza-de-la-evidencia">10. Certeza de la evidencia</h3>
<p>En salud se usa el sistema <strong>GRADE</strong> para juzgar cuánta confianza merece cada conclusión (alta, moderada, baja o muy baja), considerando el riesgo de sesgo, la inconsistencia, la imprecisión, la evidencia indirecta y el sesgo de publicación.</p>
</section>
<section id="reporte" class="level3">
<h3 class="anchored" data-anchor-id="reporte">11. Reporte</h3>
<p>Se escribe siguiendo <strong>PRISMA 2020</strong>, que vemos a continuación.</p>
</section>
</section>
<section id="qué-es-prisma" class="level2">
<h2 class="anchored" data-anchor-id="qué-es-prisma">8.3 ¿Qué es PRISMA?</h2>
<p><strong>PRISMA</strong> (<em>Preferred Reporting Items for Systematic reviews and Meta-Analyses</em>) es una <strong>guía de reporte</strong>: indica qué información tiene que contener el informe de una revisión sistemática para que los lectores puedan entender qué se hizo, evaluarlo y reproducirlo. Su versión vigente es <strong>PRISMA 2020</strong> (Page et al., 2021a), que actualizó la de 2009. Existe una traducción oficial al español (Page et al., 2021b).</p>
<div class="callout callout-style-default callout-important callout-titled" title="PRISMA no es un método para hacer revisiones: es una guía para contarlas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Clave del caso</span>PRISMA no es un método para hacer revisiones: es una guía para contarlas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cumplir con PRISMA no garantiza que una revisión sea buena; garantiza que el lector puede juzgar si lo es. Para el <em>cómo hacer</em>, las referencias son manuales como el <em>Cochrane Handbook</em> (Higgins et al., 2024) o el <em>JBI Manual for Evidence Synthesis</em> (Aromataris et al., 2024).</p>
</div>
</div>
<p>PRISMA 2020 tiene tres componentes principales:</p>
<ol type="1">
<li><strong>Lista de verificación de 27 ítems</strong> (con subítems), organizada en siete secciones.</li>
<li><strong>Lista de verificación para resúmenes</strong> (<em>PRISMA 2020 for Abstracts</em>, 12 ítems).</li>
<li><strong>Diagrama de flujo</strong>, que muestra cuántos registros se identificaron, cribaron, excluyeron e incluyeron.</li>
</ol>
</section>
<section id="la-lista-de-verificación-prisma-2020" class="level2">
<h2 class="anchored" data-anchor-id="la-lista-de-verificación-prisma-2020">8.4 La lista de verificación PRISMA 2020</h2>
<p>Un resumen de las secciones y los ítems más importantes para quien busca:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Sección</th>
<th>Ítems</th>
<th>Qué se reporta (resumido)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Título</strong></td>
<td>1</td>
<td>Identificar el trabajo como revisión sistemática.</td>
</tr>
<tr class="even">
<td><strong>Resumen</strong></td>
<td>2</td>
<td>Resumen estructurado según PRISMA para resúmenes.</td>
</tr>
<tr class="odd">
<td><strong>Introducción</strong></td>
<td>3-4</td>
<td>Justificación y objetivos o preguntas (idealmente con PICO).</td>
</tr>
<tr class="even">
<td><strong>Métodos</strong></td>
<td>5-15</td>
<td>Criterios de elegibilidad; <strong>fuentes de información</strong> con la fecha de la última búsqueda (ítem 6); <strong>estrategia de búsqueda completa</strong> para todas las bases, registros y sitios, con filtros y límites (ítem 7); proceso de selección (ítem 8); extracción de datos; evaluación del riesgo de sesgo; métodos de síntesis; evaluación del sesgo de reporte y de la certeza de la evidencia.</td>
</tr>
<tr class="odd">
<td><strong>Resultados</strong></td>
<td>16-22</td>
<td><strong>Selección de estudios con diagrama de flujo</strong> (ítem 16), incluidos los estudios que parecían cumplir los criterios pero se excluyeron, y por qué; características de los estudios; riesgo de sesgo; resultados individuales y de las síntesis.</td>
</tr>
<tr class="even">
<td><strong>Discusión</strong></td>
<td>23</td>
<td>Interpretación, limitaciones de la evidencia y de la revisión, implicancias.</td>
</tr>
<tr class="odd">
<td><strong>Otra información</strong></td>
<td>24-27</td>
<td>Registro y protocolo; financiamiento; conflictos de interés; disponibilidad de datos, código y materiales.</td>
</tr>
</tbody>
</table>
<p>La lista completa, con su documento de explicación y ejemplos, está disponible en el sitio oficial de PRISMA y en la traducción al español.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Estrategia de búsqueda completa (ítem 7)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Pista</span>Estrategia de búsqueda completa (ítem 7)
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Completa” significa <strong>la cadena textual, tal como se ejecutó, para cada base</strong>, con los límites aplicados. No alcanza con decir “se usaron los términos <em>mindfulness</em> y <em>estrés</em>”. Por eso la bitácora del capítulo 2 es tan importante: es la materia prima de este ítem. Lo habitual es poner las cadenas en un anexo o material suplementario.</p>
</div>
</div>
</section>
<section id="el-diagrama-de-flujo-prisma-2020" class="level2">
<h2 class="anchored" data-anchor-id="el-diagrama-de-flujo-prisma-2020">8.5 El diagrama de flujo PRISMA 2020</h2>
<p>El diagrama muestra el recorrido de los registros desde la búsqueda hasta la inclusión. En PRISMA 2020 tiene tres fases —<strong>identificación</strong>, <strong>cribado</strong> e <strong>inclusión</strong>— y puede tener dos columnas: una para bases de datos y registros, y otra para otros métodos (búsqueda por citas, sitios web, organizaciones).</p>
<p>Ejemplo con los números del caso guía:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
    A["&lt;b&gt;IDENTIFICACIÓN&lt;/b&gt;&lt;br/&gt;Registros identificados en bases de datos (n = 1248)&lt;br/&gt;PubMed (n = 312) · Scopus (n = 541)&lt;br/&gt;Web of Science (n = 287) · SciELO (n = 108)"]
    B["Registros eliminados antes del cribado:&lt;br/&gt;duplicados (n = 402)"]
    C["&lt;b&gt;CRIBADO&lt;/b&gt;&lt;br/&gt;Registros cribados (n = 846)"]
    D["Registros excluidos (n = 761)"]
    E["Informes buscados para recuperar (n = 85)"]
    F["Informes no recuperados (n = 3)"]
    G["Informes evaluados para elegibilidad (n = 82)"]
    H["Informes excluidos (n = 61):&lt;br/&gt;población no pertinente (n = 22)&lt;br/&gt;intervención no basada en mindfulness (n = 17)&lt;br/&gt;sin grupo de comparación (n = 12)&lt;br/&gt;resultado no medido (n = 10)"]
    O1["&lt;b&gt;OTROS MÉTODOS&lt;/b&gt;&lt;br/&gt;Registros identificados (n = 32)&lt;br/&gt;Búsqueda por citas (n = 23) · Sitios web (n = 9)"]
    O2["Informes buscados para recuperar (n = 32)"]
    O3["Informes no recuperados (n = 2)"]
    O4["Informes evaluados para elegibilidad (n = 30)"]
    O5["Informes excluidos (n = 26):&lt;br/&gt;población no pertinente (n = 14)&lt;br/&gt;diseño no elegible (n = 12)"]
    I["&lt;b&gt;INCLUIDOS&lt;/b&gt;&lt;br/&gt;Estudios incluidos en la revisión (n = 24)&lt;br/&gt;Informes de estudios incluidos (n = 25)"]
    A --&gt; B
    A --&gt; C
    C --&gt; D
    C --&gt; E
    E --&gt; F
    E --&gt; G
    G --&gt; H
    G --&gt; I
    O1 --&gt; O2
    O2 --&gt; O3
    O2 --&gt; O4
    O4 --&gt; O5
    O4 --&gt; I
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Cómo leer los números:</p>
<ul>
<li>1.248 registros − 402 duplicados = <strong>846</strong> registros cribados.</li>
<li>846 cribados − 761 excluidos por título y resumen = <strong>85</strong> informes buscados.</li>
<li>85 − 3 no recuperados = <strong>82</strong> evaluados a texto completo; 82 − 61 excluidos = <strong>21</strong> informes incluidos desde las bases.</li>
<li>Por otros métodos: 32 − 2 no recuperados = 30 evaluados; 30 − 26 excluidos = <strong>4</strong> informes incluidos.</li>
<li>Total: 21 + 4 = <strong>25 informes</strong>, que corresponden a <strong>24 estudios</strong> (un estudio se publicó en dos artículos).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Registros, informes y estudios">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota al margen</span>Registros, informes y estudios
</div>
</div>
<div class="callout-body-container callout-body">
<p>PRISMA 2020 distingue tres unidades: un <strong>registro</strong> es una referencia en una base de datos (título, resumen); un <strong>informe</strong> es un documento (artículo, tesis, informe técnico) que describe un estudio; un <strong>estudio</strong> es la investigación en sí, que puede estar publicada en varios informes. Por eso el último recuadro puede tener dos números distintos.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Herramientas para dibujar el diagrama">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Pista</span>Herramientas para dibujar el diagrama
</div>
</div>
<div class="callout-body-container callout-body">
<p>El sitio oficial de PRISMA ofrece plantillas editables. También existe una aplicación web gratuita basada en el paquete <em>PRISMA2020</em> de R (Haddaway et al., 2022) que genera el diagrama a partir de los números. Y herramientas como Rayyan o Covidence llevan la cuenta automáticamente.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Error frecuente: números que no cierran">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Error frecuente: números que no cierran
</div>
</div>
<div class="callout-body-container callout-body">
<p>Revisá que cada recuadro sea la resta exacta del anterior. Los evaluadores lo verifican y un diagrama con cuentas que no cierran genera desconfianza sobre todo el trabajo.</p>
</div>
</div>
</section>
<section id="extensiones-de-prisma" class="level2">
<h2 class="anchored" data-anchor-id="extensiones-de-prisma">8.6 Extensiones de PRISMA</h2>
<p>PRISMA tiene extensiones para situaciones específicas. Las más útiles para la búsqueda:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Extensión</th>
<th>Para qué sirve</th>
<th>Referencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>PRISMA-S</strong></td>
<td>Reportar la <strong>búsqueda</strong> en detalle (16 ítems): bases y plataformas, registros de ensayos, búsqueda en sitios web, búsqueda por citas, contacto con autores, estrategias completas, límites, filtros validados, revisión por pares de la búsqueda, actualizaciones, fechas y gestión de duplicados.</td>
<td>Rethlefsen et al.&nbsp;(2021)</td>
</tr>
<tr class="even">
<td><strong>PRISMA-P</strong></td>
<td>Redactar el <strong>protocolo</strong> de una revisión sistemática.</td>
<td>Moher et al.&nbsp;(2015)</td>
</tr>
<tr class="odd">
<td><strong>PRISMA-ScR</strong></td>
<td>Reportar <strong>revisiones de alcance</strong> (<em>scoping reviews</em>).</td>
<td>Tricco et al.&nbsp;(2018)</td>
</tr>
<tr class="even">
<td><strong>PRISMA-NMA</strong></td>
<td>Metaanálisis en red.</td>
<td>—</td>
</tr>
<tr class="odd">
<td><strong>PRISMA-DTA</strong></td>
<td>Revisiones de precisión diagnóstica.</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>PRISMA-Equity</strong></td>
<td>Revisiones centradas en la equidad.</td>
<td>—</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="PRISMA-S es la mejor lista de control para tu búsqueda">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Pista</span>PRISMA-S es la mejor lista de control para tu búsqueda
</div>
</div>
<div class="callout-body-container callout-body">
<p>, aunque no hagas una revisión sistemática formal. Si tu sección de método responde a sus ítems, cualquier lector puede reproducir tu búsqueda.</p>
</div>
</div>
</section>
<section id="herramientas-para-gestionar-una-revisión" class="level2">
<h2 class="anchored" data-anchor-id="herramientas-para-gestionar-una-revisión">8.7 Herramientas para gestionar una revisión</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Tarea</th>
<th>Herramientas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gestión de referencias y duplicados</td>
<td>Zotero, Mendeley, EndNote (capítulo 12)</td>
</tr>
<tr class="even">
<td>Cribado colaborativo</td>
<td><strong>Rayyan</strong> (versión gratuita; permite cribado ciego entre revisores; Ouzzani et al., 2016), <strong>Covidence</strong> (suscripción)</td>
</tr>
<tr class="odd">
<td>Cribado asistido por aprendizaje automático</td>
<td><strong>ASReview</strong> (código abierto; ordena los registros según la probabilidad de ser relevantes a medida que se criban; van de Schoot et al., 2021), funciones de priorización en Rayyan y otras plataformas</td>
</tr>
<tr class="even">
<td>Extracción de datos</td>
<td>Planillas de cálculo, Covidence, formularios en línea</td>
</tr>
<tr class="odd">
<td>Diagrama de flujo</td>
<td>Plantillas de PRISMA, aplicación <em>PRISMA2020</em></td>
</tr>
<tr class="even">
<td>Metaanálisis</td>
<td>RevMan (Cochrane), R (paquetes <em>meta</em>, <em>metafor</em>), JASP, jamovi</td>
</tr>
<tr class="odd">
<td>Registro del protocolo</td>
<td>PROSPERO, OSF Registries</td>
</tr>
</tbody>
</table>
<p>El uso de inteligencia artificial en estas etapas se discute en el capítulo 10.</p>
</section>
<section id="revisión-sistemática-en-un-trabajo-de-grado" class="level2">
<h2 class="anchored" data-anchor-id="revisión-sistemática-en-un-trabajo-de-grado">8.8 ¿Revisión sistemática en un trabajo de grado?</h2>
<p>Una revisión sistemática completa requiere, como mínimo, dos revisores, acceso a varias bases de datos y varios meses de trabajo. Para una tesina o un trabajo final, lo más realista suele ser una <strong>revisión sistematizada</strong>: se adoptan los elementos que hacen la búsqueda transparente y reproducible, y se declaran las limitaciones.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Revisión sistemática</th>
<th>Revisión sistematizada (trabajo de grado)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pregunta estructurada (PICO)</td>
<td>Sí</td>
<td><strong>Sí</strong></td>
</tr>
<tr class="even">
<td>Protocolo registrado</td>
<td>Sí</td>
<td>Recomendable (aunque sea un documento interno aprobado por el director)</td>
</tr>
<tr class="odd">
<td>Búsqueda en varias bases</td>
<td>Sí, exhaustiva</td>
<td><strong>Sí</strong>, 3 o 4 bases incluidas regionales</td>
</tr>
<tr class="even">
<td>Cadenas completas reportadas</td>
<td>Sí</td>
<td><strong>Sí</strong></td>
</tr>
<tr class="odd">
<td>Búsqueda en español e inglés</td>
<td>Sí o justificación</td>
<td><strong>Sí</strong></td>
</tr>
<tr class="even">
<td>Criterios de inclusión explícitos</td>
<td>Sí</td>
<td><strong>Sí</strong></td>
</tr>
<tr class="odd">
<td>Doble revisión independiente</td>
<td>Sí</td>
<td>Parcial (p.&nbsp;ej., el director revisa una muestra)</td>
</tr>
<tr class="even">
<td>Evaluación formal del riesgo de sesgo</td>
<td>Sí</td>
<td>Opcional o simplificada</td>
</tr>
<tr class="odd">
<td>Diagrama de flujo PRISMA</td>
<td>Sí</td>
<td><strong>Sí</strong></td>
</tr>
<tr class="even">
<td>Metaanálisis</td>
<td>Si corresponde</td>
<td>Raramente</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clave del caso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Llamá a tu trabajo por su nombre. Si no hiciste doble revisión ni evaluación del riesgo de sesgo, no es una revisión sistemática en sentido estricto: es una revisión sistematizada, una revisión de la literatura con búsqueda estructurada, o una revisión de alcance si ese era el objetivo. Declararlo con honestidad fortalece tu trabajo; exagerar el método lo debilita.</p>
</div>
</div>
<hr>
</section>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<ul>
<li>Hay muchos tipos de revisiones: narrativas, sistemáticas, metaanálisis, de alcance, rápidas, paraguas y sistematizadas. Lo que las distingue es el método.</li>
<li>Una revisión sistemática sigue etapas definidas: pregunta, protocolo, búsqueda, cribado, evaluación, extracción, riesgo de sesgo, síntesis, certeza y reporte.</li>
<li>PRISMA 2020 es una guía para <strong>reportar</strong> revisiones: 27 ítems, una lista para resúmenes y un diagrama de flujo en tres fases (identificación, cribado, inclusión).</li>
<li>PRISMA-S detalla cómo reportar la búsqueda y es útil para cualquier trabajo; PRISMA-P sirve para protocolos y PRISMA-ScR para revisiones de alcance.</li>
<li>En un trabajo de grado, una revisión sistematizada bien documentada es una meta realista y valiosa.</li>
</ul>
</section>
<section id="actividad" class="level2">
<h2 class="anchored" data-anchor-id="actividad">Actividad</h2>
<ol type="1">
<li>Buscá una revisión sistemática publicada sobre tu tema y ubicá: la pregunta, las bases usadas, la cadena de búsqueda completa y el diagrama de flujo. ¿Cumple con el ítem 7 de PRISMA (estrategia completa)?</li>
<li>Verificá las cuentas de su diagrama de flujo.</li>
<li>Redactá un mini protocolo de una página para tu propia búsqueda: pregunta PICO, criterios de inclusión y exclusión, bases de datos, idiomas, período y plan de selección.</li>
<li>Con los resultados de tu búsqueda (aunque sea preliminar), armá un diagrama de flujo PRISMA.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/07-pregunta-pico.html" class="pagination-link" aria-label="Capítulo 7. La pregunta PICO y sus variantes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Capítulo 7. La pregunta PICO y sus variantes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/09-busqueda-por-citas.html" class="pagination-link" aria-label="Capítulo 9. Búsqueda por citas y estrategias complementarias">
        <span class="nav-page-text"><span class="chapter-title">Capítulo 9. Búsqueda por citas y estrategias complementarias</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Buscar antecedentes · un caso a la vez</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>